# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: Nicholas Clark
title: Nicholas Clark
status: Carnegie Mellon University School of Computer Science
email: nicholas@californiaclarks.com
intro: >
  I’m a Carnegie Mellon University School of Computer Science student, who’s developed an unwavering passion for science and technology long before I stepped on campus. Throughout grade-school I competed in a variety of local and regionally recognized robotic and cyber security opportunities. While developing strong technical skills was a byproduct of my involvement, I also grew as an individual, with strong interpersonal skills, and a passion for working with others to solve challenging problems.


  My high school years were a discovery period in which I began to explore the cross-sections of classroom theory and practical applications to solving real problems. Through after-school programs and college courses, I developed proficiencies in programming languages and began sharing my software skills with non-profit organizations serving my community.


  As a college student, I’m incredibly grateful to be a part of the Carnegie Mellon University School of Computer Science. The education, community, and opportunities available continue to serve my never-ending-thirst to continue growing towards a career in computer science. The culmination of my varied experiences have contributed towards establishing my voice and the person I’ve become, and as our campus mantra goes, “My Heart Is in the Work”.
contact-msg: >
  Academics consume a great part of my days. However I make a concerted effort to respond to all correspondance in a timely manner.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  najclark

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
